### ISSUE TITLE
CORS policy !!

### ISSUE THREAD

**Issue by sigalou** [mulder82/immich-slideshow#4]
Hi !!

_Access to fetch at 'http://192.168.1.2:2283/api/asset/random' from origin 'http://homeassistant.local:8123' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled._

I have worked a lot to try to understand my problem but I still have a blockage.
I even tried putting nginx as a reverse proxy server to add Access-Control-Allow-Origin, nothing worked. Requests like /api/asset/random work fine with postman but not with Home Assistant.
The fetch is systematically in error.

I have the right API socket, I have the right address, the right port. When I do the same query as fetch in Postma, it works. When I do it in curl in cli, same, it's ok

I tested other requests that respond in json, they work well, only those sent to immit are blocked.
I don't understand, do you have a card that works?

thank!

**Comment by mulder82** [comment]
Hi, 

I had identical problems while creating this add-on. The solutions are two: 

1) Modify the immich server to send the appropriate [HTTP CORS headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS)

2) Run chromium browser with the appropriate parameters so that it does not check the cors rules:
```console
chromium-browser --disable-web-security --user-data-dir=“[some directory here]”
```
I personally use the latter option and everything works very stably. 

My command to run chromium in kiosk mode look like this:
```console
/usr/bin/chromium-browser --noerrdialogs --disable-infobars --ignore-certificate-errors --allow-running-insecure-content --disable-web-security --user-data-dir=/home/sadm/kiosk/chrome-profile --kiosk https://192.168.1.100:8123/dashboard-verbatim/home?kiosk
```
